//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class akcia
    {
        public int id_akcie { get; set; }
        public int id_menu { get; set; }
        public int id_podniku { get; set; }
        public Nullable<int> id_obrazka { get; set; }
        public Nullable<int> text_id { get; set; }
        public System.DateTime platnost_od { get; set; }
        public System.DateTime platnost_do { get; set; }
        public Nullable<int> akciova_cena { get; set; }
    
        public virtual text text { get; set; }
        public virtual menu menu { get; set; }
        public virtual obrazok obrazok { get; set; }
    }
}
