//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class jedlo
    {
        public jedlo()
        {
            this.menu_jedlo = new HashSet<menu_jedlo>();
            this.jedlo_surovina = new HashSet<jedlo_surovina>();
        }
    
        public int id_jedla { get; set; }
        public int nazov { get; set; }
        public int id_typu { get; set; }
        public Nullable<int> mnozstvo_kalorii { get; set; }
        public Nullable<int> dlzka_pripravy { get; set; }
    
        public virtual ICollection<menu_jedlo> menu_jedlo { get; set; }
        public virtual ICollection<jedlo_surovina> jedlo_surovina { get; set; }
        public virtual typ_jedla typ_jedla { get; set; }
        public virtual text text { get; set; }
    }
}
