//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public menu()
        {
            this.akcia = new HashSet<akcia>();
            this.denne_menu = new HashSet<denne_menu>();
            this.menu_jedlo = new HashSet<menu_jedlo>();
            this.menu_napoj = new HashSet<menu_napoj>();
            this.objednavka_menu = new HashSet<objednavka_menu>();
        }
    
        public Nullable<int> text_id { get; set; }
        public int id_menu { get; set; }
        public int id_podniku { get; set; }
        public Nullable<int> id_obrazka { get; set; }
        public Nullable<int> nazov { get; set; }
        public Nullable<int> typ_platnosti { get; set; }
    
        public virtual ICollection<akcia> akcia { get; set; }
        public virtual ICollection<denne_menu> denne_menu { get; set; }
        public virtual ICollection<menu_jedlo> menu_jedlo { get; set; }
        public virtual ICollection<menu_napoj> menu_napoj { get; set; }
        public virtual podnik podnik { get; set; }
        public virtual ICollection<objednavka_menu> objednavka_menu { get; set; }
        public virtual obrazok obrazok { get; set; }
        public virtual text text { get; set; }
        public virtual text text1 { get; set; }
        public virtual platnost_zaznamu platnost_zaznamu { get; set; }
    }
}
