//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_napoj
    {
        public int id_napoja { get; set; }
        public int id_menu { get; set; }
        public double cena { get; set; }
        public double mnozstvo { get; set; }
        public int id_podniku { get; set; }
    
        public virtual menu menu { get; set; }
        public virtual napoj napoj { get; set; }
    }
}
