//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class objednavka
    {
        public objednavka()
        {
            this.objednavka_menu = new HashSet<objednavka_menu>();
        }
    
        public int id_objednavky { get; set; }
        public int id_stola { get; set; }
        public int id_uctu { get; set; }
        public System.DateTime datum_objednania { get; set; }
        public Nullable<int> potvrdena { get; set; }
        public Nullable<System.DateTime> datum_zaplatenia { get; set; }
        public double suma { get; set; }
    
        public virtual stol stol { get; set; }
        public virtual ICollection<objednavka_menu> objednavka_menu { get; set; }
        public virtual ucet ucet { get; set; }
    }
}
