//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class objednavka_menu
    {
        public int id_polozky { get; set; }
        public int id_menu { get; set; }
        public int id_objednavky { get; set; }
        public int id_podniku { get; set; }
    
        public virtual menu menu { get; set; }
        public virtual objednavka objednavka { get; set; }
    }
}
