//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class otvaracie_hodiny
    {
        public int id_podniku { get; set; }
        public int cislo_dna { get; set; }
        public System.DateTime cas_otvorenia { get; set; }
        public int doba_otvorenia { get; set; }
    
        public virtual den_v_tyzdni den_v_tyzdni { get; set; }
        public virtual podnik podnik { get; set; }
    }
}
