//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class platnost_zaznamu
    {
        public platnost_zaznamu()
        {
            this.menu = new HashSet<menu>();
        }
    
        public int typ_platnosti { get; set; }
    
        public virtual ICollection<menu> menu { get; set; }
    }
}
