//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class preklad
    {
        public string kod_jazyka { get; set; }
        public int text_id { get; set; }
        public string preklad1 { get; set; }
    
        public virtual jazyk jazyk { get; set; }
        public virtual text text { get; set; }
    }
}
