//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class stol
    {
        public stol()
        {
            this.objednavka = new HashSet<objednavka>();
        }
    
        public int id_stola { get; set; }
        public int pocet_miest { get; set; }
    
        public virtual ICollection<objednavka> objednavka { get; set; }
    }
}
