//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class surovina
    {
        public surovina()
        {
            this.jedlo_surovina = new HashSet<jedlo_surovina>();
            this.napoj_surovina = new HashSet<napoj_surovina>();
        }
    
        public int id_surovina { get; set; }
        public int nazov { get; set; }
        public int alergen { get; set; }
        public string jednotka { get; set; }
        public int platna { get; set; }
    
        public virtual ICollection<jedlo_surovina> jedlo_surovina { get; set; }
        public virtual ICollection<napoj_surovina> napoj_surovina { get; set; }
        public virtual text text { get; set; }
    }
}
