//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class text
    {
        public text()
        {
            this.akcia = new HashSet<akcia>();
            this.den_v_tyzdni = new HashSet<den_v_tyzdni>();
            this.jedlo = new HashSet<jedlo>();
            this.menu = new HashSet<menu>();
            this.menu1 = new HashSet<menu>();
            this.napoj = new HashSet<napoj>();
            this.preklad = new HashSet<preklad>();
            this.surovina = new HashSet<surovina>();
            this.typ_jedla = new HashSet<typ_jedla>();
            this.typ_napoja = new HashSet<typ_napoja>();
        }
    
        public int text_id { get; set; }
    
        public virtual ICollection<akcia> akcia { get; set; }
        public virtual ICollection<den_v_tyzdni> den_v_tyzdni { get; set; }
        public virtual ICollection<jedlo> jedlo { get; set; }
        public virtual ICollection<menu> menu { get; set; }
        public virtual ICollection<menu> menu1 { get; set; }
        public virtual ICollection<napoj> napoj { get; set; }
        public virtual ICollection<preklad> preklad { get; set; }
        public virtual ICollection<surovina> surovina { get; set; }
        public virtual ICollection<typ_jedla> typ_jedla { get; set; }
        public virtual ICollection<typ_napoja> typ_napoja { get; set; }
    }
}
