//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class typ_uctu
    {
        public typ_uctu()
        {
            this.ucet = new HashSet<ucet>();
        }
    
        public int id { get; set; }
        public string nazov { get; set; }
    
        public virtual ICollection<ucet> ucet { get; set; }
    }
}
