//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class typ_napoja
    {
        public typ_napoja()
        {
            this.napoj = new HashSet<napoj>();
        }
    
        public int id_typu { get; set; }
        public int text_id { get; set; }
    
        public virtual text text { get; set; }
        public virtual ICollection<napoj> napoj { get; set; }
    }
}
