//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ucet
    {
        public ucet()
        {
            this.objednavka = new HashSet<objednavka>();
        }
    
        public int id_uctu { get; set; }
        public int id { get; set; }
        public string login { get; set; }
        public string heslo { get; set; }
    
        public virtual ICollection<objednavka> objednavka { get; set; }
        public virtual typ_uctu typ_uctu { get; set; }
    }
}
